### ISSUE TITLE
Laravel 5 compatibility?

### ISSUE THREAD

**Issue by dhardtke** [fedeisas/laravel-js-routes#15]
Hey,

thanks for your awesome Laravel 4 package.
I was using it for a long time and right now I am working on my app to make it Laravel 5 compatible.
Hence my question: is this package Laravel 5 compatible?

Thanks.

Edit:
Okay, tried installing and I'm getting:
> Your requirements could not be resolved to an installable set of packages.

**Comment by fedeisas** [comment]
@dhardtke Hi! I'm just getting into L5. I'll try to make this compatible. Thanks!

**Comment by venanciorodrigo** [comment]
+ 1

**Comment by venanciorodrigo** [comment]
+1

**Comment by slider23** [comment]
+1

**Comment by prYmea** [comment]
+1

**Comment by dhardtke** [comment]
Any news on this?
